windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = true
}

# make gwenview open (when screenshot) as a floating window
windowrule {
    name = screenshot-float
    match:class = ^(org.kde.gwenview)$
    float = true
    size = 960 540
    center = true
}

windowrule {
    name = file-picker-float
    match:class = ^(xdg-desktop-portal-gtk)$
    float = true
    size = 960 600
    center = true
    opacity = 0.9 0.9 0.9
}

# make network manager float (nm-connection-editor)
windowrule {
    name = nm-float
    match:class = ^(nm-connection-editor)$
    float = true
    size = 1400 800
    center = true
    opacity = 0.85 0.85 0.85
}

# make blueman float
windowrule {
    name = blueman-float
    match:class = ^(blueman-manager)$
    float = true
    size = 1400 800
    center = true
    opacity = 0.85 0.85 0.85
}

# stop wezterm blur
windowrule {
    name = wezterm-no-blur
    match:class = ^(org.wezfurlong.wezterm)$
    no_blur = true
}

windowrule {
    name = dolphin-blur
    match:class = ^(org.kde.dolphin)$
    opacity = 0.85 0.85
}

# disable rounding for fullscreen applications
windowrule {
    name = fullscreen-no-rounding
    match:fullscreen = true
    rounding = 0
}

windowrule {
    name = discord-popup
    match:initial_title = ^(Discord Popout)$
    float = true
    size = 640 380
    center = true
}

layerrule {
    name = wlogout-blur
    match:namespace = logout_dialog
    blur = true
}

