general {
    before_sleep_cmd = hyprlock
    ignore_dbus_inhibit = false
}

# Dim screen after 3 minutes
# listener {
#     timeout = 180
#     on-timeout = brightnessctl -s set 35%
#     on-resume = brightnessctl -r
# }

# Lock after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Suspend after 8 minutes
# listener {
#     timeout = 480
#     on-timeout = systemctl suspend
# }
