AUR_PKGS=(
    # terminal
    wezterm-git

    # browser
    zen-browser-bin

    # misc file opener/editor
    onlyoffice-bin

    # alternative editor
    vscodium-bin

    # DE helpers
    wlogout
    # orbit-wifi
    waybar-weather

    # screenshot helper
    grimblast
)
