PACMAN_PKGS=(
    # system
    base-devel
    coreutils
    git
    curl
    wget
    zip
    unzip
    7zip
    networkmanager
    network-manager-applet
    bluez
    bluez-utils
    pipewire
    pipewire-pulse
    pipewire-alsa

    # DE
    hyprland
    waybar
    rofi
    swaync
    awww
    hypridle
    hyprlock
    wl-clipboard

    # sddm (silent theme dependencies)
    sddm
    qt6-svg
    qt6-virtualkeyboard
    qt6-multimedia-ffmpeg
    qt6-imageformats

    # terminal + shell
    # wezterm # using wezterm-git from aur
    zsh
    zsh-syntax-highlighting
    zsh-autosuggestions
    starship
    ttf-cascadia-mono-nerd
    noto-fonts
    noto-fonts-emoji
    noto-fonts-cjk
    noto-fonts-extra

    # cli tools
    fzf
    zoxide
    eza
    bat
    fd
    fastfetch
    yazi
    ffmpeg
    jq
    poppler
    resvg
    imagemagick
    man
    tldr
    lazygit
    ncdu

    # text editor
    neovim

    # development tools
    clang
    make
    cmake
    gcc
    python
    python-pip
    uv
    nodejs
    npm
    typescript
    jdk21-openjdk
    go
    rustup
    typst

    # apps
    dolphin
    obs-studio
    spotify-launcher
    discord
    gwenview
    obsidian
    # gimp
    # krita
    kolourpaint
    blender
)
