PACMAN_PKGS=(
    # system
    base-devel
    coreutils
    git
    curl
    wget
    zip
    unzip
    7zip
    networkmanager
    network-manager-applet
    bluez
    bluez-utils
    pipewire
    pipewire-pulse
    pipewire-alsa

    # DE
    hyprland
    waybar
    swaync
    awww
    hypridle
    hyprlock
    wl-clipboard

    # terminal + shell
    wezterm
    zsh
    zsh-syntax-highlighting
    zsh-autosuggestions
    starship
    ttf-cascadia-mono-nerd
    noto-fonts
    noto-fonts-emoji

    # cli tools
    fzf
    zoxide
    eza
    bat
    fd
    fastfetch
    yazi
    ffmpeg
    jq
    poppler
    resvg
    imagemagick
    man
    tldr

    # text editor
    neovim

    # development tools
    clang
    gcc
    python
    python-pip
    uv
    nodejs
    npm
    typescript
    jdk21-openjdk
    go
    rustup

    # apps
    dolphin
    discord
    gwenview
    # gimp
    # krita
)
